# Generated by Django 3.1.4 on 2021-01-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_class', models.CharField(max_length=30, verbose_name='主类')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('model', models.CharField(max_length=30, verbose_name='型号')),
                ('price', models.FloatField(verbose_name='市场价')),
                ('cost', models.FloatField(verbose_name='成本价')),
                ('sub_class', models.CharField(blank=True, max_length=30, verbose_name='子类')),
                ('brand', models.CharField(blank=True, max_length=30, verbose_name='品牌')),
                ('suppiler', models.CharField(blank=True, max_length=30, verbose_name='供应商')),
                ('inner_model', models.CharField(blank=True, max_length=30, verbose_name='内部型号')),
                ('unit', models.CharField(blank=True, max_length=5, verbose_name='单位')),
                ('picture', models.CharField(blank=True, max_length=100, verbose_name='图片')),
                ('product_page', models.CharField(blank=True, max_length=100, verbose_name='产品页')),
                ('introduce', models.TextField(blank=True, max_length=300, verbose_name='简介')),
                ('link', models.CharField(blank=True, max_length=100, verbose_name='链接')),
                ('level', models.SmallIntegerField(blank=True, choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'S')], verbose_name='产品等级')),
                ('inventory', models.IntegerField(blank=True, null=True, verbose_name='库存')),
                ('note', models.TextField(blank=True, max_length=300, verbose_name='备注')),
                ('created_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'db_table': 'products',
            },
        ),
    ]
